### ISSUE TITLE
Is there a way to return an Error? like HTTP_400_BAD_REQUEST

### ISSUE THREAD

**Issue by sainoba** [MattBroach/DjangoRestMultipleModels#10]
First of all thanks for the work. I really like the poject.

So my question is
Is there any way to return something else than a list with a 200 succes code? something like `HttpResponseBadRequest` or  `HttpResponseForbidden`

The most I could do was to `raise Http404` but nothing else.

**Comment by MattBroach** [comment]
Could you tell me a little bit more about what kind of response you'd like to get?  Since the `MultipleModelAPIView` inherits from Django Rest Framework's `GenericAPIView`, it can raise a 301 and other permission errors by using the DRF permission classes (eg `IsAuthenticated`, `IsAdminUser`, etc).  Is that the kind of thing you're looking for, or do you want something else?

**Comment by MattBroach** [comment]
Since I never got a follow up, closing this for now.  If you have clarification, feel free to reopen.
