### ISSUE TITLE
Paginations

### ISSUE THREAD

**Issue by dmsnet** [MattBroach/DjangoRestMultipleModels#34]
Can i paginate all results queryset?  without per queryset pagination .

**Comment by MattBroach** [comment]
Unfortunately, pagination can only be provided at the queryset level.  Earlier incarnations of this library (pre-2.0) had pagination on all results, but it had to be discarded.  The problem was that the __primary__ benefit of pagination is not in limiting the number of items return via the API but in limiting the number of items fetched from the database, which is usually where the big performance cost usually is.  Given that, it's impossible to __truly__ paginatate the overall results because the querysets have to be evaluated before they can be merged.

If you'd like to re-implement a version of the all-results pagination for your own code, you can take a look at how it [used to be implemented](https://github.com/MattBroach/DjangoRestMultipleModels/blob/b05eee77512e1dfeb56c5b5a83a8bb702477c609/drf_multiple_model/mixins.py#L70). Basically, you just need to call `paginate_queryset` on the results (assuming they haven't already been paginated, and that the `pagination_class` isn't one from `DjangoRestMultipleModels`).  I think the use case is probably narrow enough, though, that it's not going to go back into the library as it currently exists.
