### ISSUE TITLE
Can I using it in modelviewset?

### ISSUE THREAD

**Issue by lyquita** [MattBroach/DjangoRestMultipleModels#53]
I just noticed it's kind of api view tool.

**Comment by MattBroach** [comment]
I think it wouldn't make sense to use this in a ModelViewSet, since the point of the ModelViewSet is to automatically generate a viewset based on a model and a serializer.  The DjangoRestMultipleModels mixins bypass all of the steps under the hood that do that kind of automagic viewset generation, so you wouldn't be gaining any of the benefits of using a ModelViewSet.

Also, as pointed out in another issue, the `create` and `update` methods for a `queryList` are currently undefined, so this could lead to some wonky or broken behavior when integrating this library into a ModelViewSet.
